# Generated by Django 3.2.15 on 2023-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Охранник')], null=True, verbose_name='Роль'),
        ),
    ]
