# Generated by Django 3.2.15 on 2023-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230128_1730'),
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cameras',
            field=models.ManyToManyField(to='app.Camera'),
        ),
    ]
