# Generated by Django 3.2.15 on 2023-01-28 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('camtype', models.IntegerField(default=1, verbose_name='Тип камеры (1-3)')),
                ('ip_address', models.CharField(max_length=32, verbose_name='IP адрес')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('full_name', models.CharField(max_length=512, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='employee', verbose_name='Фото')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=256, verbose_name='Наименование')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('employees', models.ManyToManyField(blank=True, null=True, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=4096, verbose_name='Название')),
                ('coordinates', models.CharField(max_length=64, verbose_name='Координаты места')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='TourniquetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('state', models.IntegerField(choices=[(1, 'Открыт'), (2, 'Закрыт')], default=2, verbose_name='Состояние')),
                ('ip_address', models.CharField(max_length=32, verbose_name='IP адрес')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Расположение')),
            ],
        ),
        migrations.CreateModel(
            name='TourniquetTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('start_time', models.TimeField(verbose_name='Время начала доступа')),
                ('end_time', models.TimeField(verbose_name='Конец начала доступа')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee', verbose_name='Сотрудник')),
                ('tourniquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tourniquetlock', verbose_name='Турникет')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGroupTimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('start_time', models.TimeField(verbose_name='Начало времени доступа')),
                ('end_time', models.TimeField(verbose_name='Окончание времени доступа')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('employee_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeegroup', verbose_name='Группа сотрудников')),
                ('tourniquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tourniquetlock', verbose_name='Турникет')),
            ],
        ),
        migrations.CreateModel(
            name='CameraToTourniquetLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid5, editable=False, unique=True, verbose_name='UUID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateField(auto_now=True, verbose_name='Обновлен')),
                ('cameras', models.ManyToManyField(to='app.Camera')),
                ('tourniquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tourniquetlock', verbose_name='Турникет')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Расположение'),
        ),
    ]
